Repository oslc-op/oslc-specs, pull requests merged in 2020-08, with the labels that each got.

#391 Update README.md to be in sync with the code
  tools/ShapeChecker/README.md
Labels: Tool: ShapeChecker

#404 Fix W3C validation errors in QM
  specs/qm/quality-management-shapes.html
  specs/qm/quality-management-spec.html
  specs/qm/quality-management-vocab.html
Labels: Area: Domains, Domain: QM

#413 B config mgmt
  specs/config/README.md
  specs/config/config-resources.html
  specs/config/config-shapes.ttl
  specs/config/config-vocab.html
  specs/config/config-vocab.ttl
  specs/config/oslc-config-mgt.html
  specs/config/readme.html
  specs/config/versioned-resources.html
Labels: Domain: CfgM, Kind: Editorial, Kind: Formatting
